import { Full_Poem, Line, Word, Line_Alignment } from "../../app/poem/poem_classes";

let full_poem_text = [
"bifurcate me.",
"vi vi ⠀ ⠀ ⠀",
"sect me.",
"sep     ⠀⠀   ",
"ar",
"ate my self.",
"my halves are dist ⠀ ⠀ ⠀ ⠀ ⠀ ⠀ ⠀ ⠀ ⠀ ⠀ ⠀",
"inct ",
"and un    ⠀⠀⠀⠀⠀",
"i",
"qué?",
"",
"trifurcate me.",
"i am threee.",
"me, myself, and",
"i am so tired of being coooped up in",
"my head hurts.",
"past, present, fut",
"u’re not aw",
"are you listening?",
"",
"quadfurcate me.",
"my four lives do not inter                ",
"sect me.",
"race",
"gender",
"sex        ",
"uality",
"⠀cl    ",
"⠀        ⠀assk me what çountry",
"i",
"qué ⠀ ⠀ ⠀ ⠀",
"ame from?",
"",
"quinfurcate me.",
"i",
"h",
    "⠀⠀⠀⠀ate my self",
"and un    ⠀    ⠀",
"cl",
"⠀⠀e",
"sam",
"wasn’t made for my five selves.",
"my origin obscured",
"your inst    ",
"inct",
"to deny ",
"me, myself, and",
"my family.",
"if my dad had bad engl            ",
"⠀⠀i",
"shh",
"would you listen?",
"",
"sex    ",
"furcate",
"me.",
"",
"sep    ",
"furcate",
"me.",
"",
"mult ⠀ ⠀ ⠀",
"i",
"furcate",
"me.",
"",
"please.",
"",
"atomize me.",
"drop me by the fingertips and let the ",
"wind whisk my sinned bits wayward.",
"i’ll return to whence i came",
"and my infinite selves will no longer buzz in your ears.",
"i’ll be whole somewhere,",
"in a land where my brown husband’s name",
"has all the little acçents and ligatures,",
"and i can distribute my wealth to my poor relatives",
"who don’t speak english.",
"and when they tell me their problems",
"and i still dwell on mine,",
"they’ll ask, meek intonations lulling me to sleep,",
"",
"kendİnİ dİnledİn",
"me?"
]

export const full_poem = new Full_Poem()
full_poem.parsePoem("FuRcAtEd", full_poem_text, "February 2018", Line_Alignment.CENTER);
full_poem.lines[0].words[0] = new Word("bifurcate", '', ' ', 'split into 2', [], [0], ['bI', "f.R", "kAt"], ['BUY', 'fur', 'kate']);
full_poem.lines[1].words[0] = new Word("vi", '', ' ', 'vivisect = dissect while alive', [], [0], ['vi', 'vi', 'sekt'], ["VIH", "vih", "sekt"]);
full_poem.lines[10].words[0] = new Word("qué", '', '?', "Spanish for 'what'", [], [0], ['kA'], ["KAY"]);
full_poem.lines[12].words[0] = new Word("trifurcate", '', ' ', 'split into 3', [], [0], ['trI', "f.R", "kAt"], ['TRY', 'fur', 'kate']);
full_poem.lines[81].words[2] = new Word("meek", '', ' ', 'shy, timid', [], [0], ['mEk'], ['MEEK']);
full_poem.lines[81].words[3] = new Word("intonations", '', ' ', 'vocal fluctuations during speech', [], [2], ['in', 'tO', 'nA', 'S.nz'], ['intone', 'NATions']);
full_poem.lines[83].words[0] = new Word("kendİnİ", '', ' ', "kendini dinledin mi = Turkish for 'did you listen to yourself?'");
