import { Full_Poem, Line_Alignment, Word } from "../../app/poem/poem_classes";

let full_poem_text = [
"when Joey died, he took red with him",
"the beauty of viscera is best appreciated",
"in the bodies of strangers",
"how a bloody brain in your friend's skull is less",
"fun than the one on liveleak",
"the air in that hospital room was evacuated",
"of all life, leaving a scarlet splatter scene",
"in the gasping dust motes",
"what is left of a boy who became a box ",
"of sillybandz ",
"what is left of the reflections in his eyes",
"swollen shut",
"what is left of a boy neurosurgeon who",
"voted gore at the kids choice awards",
"and summoned it thru the tv screen",
"to butcher his friend",
"red was my favorite color",
"i was gonna be a doctor",
"",
"the blue sky casts itself into the inken",
"waves, alight the birdfish in the",
"gullets of whales and sh",
"arks, , , spin a sanguine flyer",
"up and through and out, explode",
"chunks of flesh thru the eye of a needle",
"how many dead boys fit on the head of a pin",
"too many, too many, too many, too young",
"",
"the red shadow on a blue mirror",
"leaks jetski fuel into itself, expands",
"a pseudopod emerges, spreads, descends",
"and morphs, an amoeboid charon",
"of blood clotting effortlessly in the wide veins",
"of the sea, clotting effortlessly in the narrow veins",
"of",
"",
"bright baby blue, bright baby Joe",
"did your sillybandz set have an angel?",
"what color was it?",
"what color was it?",
"",
"i've reeled out my intestines like",
"chum into the mottled streets",
"and fished for the colors i left on the sidewalk",
"when i tried to become a chalk outline",
"i've scraped my skin to the dermis",
"just to see if what i leak remains red",
"the final word of any meaning in a",
"decomposing cerebrum, a triptych of",
"God's name being whispered by the sun rays",
"i prayed for you and then you died",
"",
"when i died i saw blue",
"when i died i was blue",
"hooloovoo, let live the blue",
"hooloovoo, hooloovoo, hooloovoo",
"",
"it won't leave me, the blood, the red, his",
"face, his death, his rest",
"what is the sum of blood and seawater?",
"god it's purple, isn't it?",
"fucking faggot"
]

export const full_poem = new Full_Poem()
full_poem.parsePoem("on mourning a friend and a favorite color", full_poem_text, "July 10, 2023", Line_Alignment.CENTER);