import { Full_Poem, Line, Word } from "../../app/poem/poem_classes";

let full_poem_text = [
"what do you do when there is nothing",
"to be done, when the words you’ve so cultivated well",
"up like a swarm of locusts behind your glottis, when",
"a fresh pop of mucus is the only sound you can",
"produce how do you sit still",
"in the vibrating chasm between suicides",
"when the only heat is the spitting hearth of",
"cirrhosis",
"",
"what do you say when every act of",
"saying deletes a day from your memory when",
"the companionship of silence runs out and he",
"leaves you in a deader air than you could have",
"produced from between your ears when the gunshots ",
"come from inside your skull and you want to",
"puncture your eardrum like popping a bullet’s",
"pimple",
"",
"where do you live when your skin abandons",
"you, when bit by bit each finger slices itself",
"off a hand unrecognizable as its source",
"when your tongue cuts your gums each ",
"time you flick it in preparation for something you ",
"know will never happen but will somehow still",
"make everyone you love turn towards the sun",
"and leap, as if you have become the moon and",
"they the tides you mangle against the",
"shore ",
"",
"where does the violence go when the glaciers finall",
"y reach your toes and begin peeling your toenails off",
"like labels on pears, when every smell is inverted a",
"nd the scripts you spent so long learning have been",
"redacted in favor of a type of dance known by",
"no one but performed at you each day by the rising",
"sun ",
"",
"who do you kill when all that’s left is you and every",
"body you’ve already discarded for being",
"too hard to skin, what is your name when the paper",
"enveloping you rots away and leaves a set of",
"rings and a few coins, what time is it when",
"you’ve always just died and are tired of being",
"reborn"
]

export const full_poem = new Full_Poem()
full_poem.parsePoem("skinner box", full_poem_text, "August 18, 2022");
